/**
 * Miscellaneous comment and message formatting helpers.
 * Mirrors agent/utils/comments.py
 */

/**
 * Build the standard agent attribution footer for PR bodies / comments.
 */
export function agentFooter(runId?: string): string {
  const parts = ["\n\n---\n*Generated by [Open SWE JS](https://github.com/langchain-ai/open-swe)*"];
  if (runId) {
    const url = runUrl(runId);
    if (url) parts.push(` · [View run](${url})`);
  }
  return parts.join("");
}

function runUrl(runId: string): string | null {
  const hostUrl = (
    process.env.LANGFUSE_BASE_URL ??
    process.env.LANGFUSE_HOST ??
    "https://cloud.langfuse.com"
  ).replace(/\/+$/, "");
  const projectId = process.env.LANGFUSE_PROJECT_ID;
  if (!projectId) return null;
  return `${hostUrl}/project/${projectId}/traces/${runId}`;
}

/**
 * Truncate a string to maxLength, appending "..." if trimmed.
 */
export function truncate(text: string, maxLength = 1000): string {
  if (text.length <= maxLength) return text;
  return `${text.slice(0, maxLength - 3)}...`;
}

/**
 * Extract the first line of a string (for use as PR title prefix / log lines).
 */
export function firstLine(text: string): string {
  return text.split("\n")[0].trim();
}
