/**
 * Miscellaneous comment and message formatting helpers.
 * Mirrors agent/utils/comments.py
 */

/**
 * Build the standard agent attribution footer for PR bodies / comments.
 */
export function agentFooter(runId?: string): string {
  const parts = ["\n\n---\n*Generated by [Open SWE JS](https://github.com/langchain-ai/open-swe)*"];
  if (runId) {
    parts.push(` · [View run](${runUrl(runId)})`);
  }
  return parts.join("");
}

function runUrl(runId: string): string {
  const langsmithUrl = process.env.LANGSMITH_URL ?? "https://smith.langchain.com";
  return `${langsmithUrl}/runs/${runId}`;
}

/**
 * Truncate a string to maxLength, appending "..." if trimmed.
 */
export function truncate(text: string, maxLength = 1000): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + "...";
}

/**
 * Extract the first line of a string (for use as PR title prefix / log lines).
 */
export function firstLine(text: string): string {
  return text.split("\n")[0].trim();
}
